CREATE TRIGGER TRG_ATUALIZA_PRECO
 ON DBO.PRODUTOS
 FOR UPDATE AS 
 IF UPDATE(PRECO)

 BEGIN 
          DECLARE @IDPRODUTO INT
          DECLARE @PRODUTO   VARCHAR (30)
          DECLARE @CATEGORIA VARCHAR (10)
          DECLARE @PRECO NUMERIC(10,2)
          DECLARE @PRECONOVO NUMERIC(10,2)
          DECLARE @DATA DATETIME 
          DECLARE @USUARIO VARCHAR (30)
          DECLARE @ACAO VARCHAR (100)


          SELECT @IDPRODUTO = IDPRODUTO FROM INSERTED
          SELECT @PRODUTO   = PRODUTO   FROM INSERTED
          SELECT @CATEGORIA = CATEGORIA FROM INSERTED
          SELECT @PRECO     = PRECO     FROM DELETED
          SELECT @PRECONOVO = PRECO     FROM INSERTED
          

          SET @DATA    = GETDATE()
          SET @USUARIO = SUSER_NAME()
          SET @ACAO    = 'VALOR INSERIDO PELA TRIGGER TRG_ATUALIZA_PRECO'

          INSERT INTO HOSTORICO
          (PRODUTO,CATEGORIA,PRECOANTIGO, PRECONOVO,DATA, USUARIO,MENSAGEM)
          VALUES
          (@PRODUTO,@CATEGORIA,@PRECOANTIGO,@PRECONOVO,@DATA,@USUARIO,@ACAO)

          PRINT 'TRIGGER EXECUTADA COM SUCESSO'

 END

 UPDATE PRODUTOS 
 SET PRECO = 300.00
 WHERE IDPRODUTO = 2
 GO

 UPDATE PRODUTOS SET NOME = 'LIVRO JAVA'
 WHERE IDPRODUTO = 2
 
CREATE TRIGGER TGR_ATUALIZA_NOME
ON DBO.PRODUTOS
FOR UPDATE AS 
IF UPDATE(NOME)
BEGIN
    DECLARE  @PRODUTO   VARCHAR(50)
	DECLARE  @PRODUTONOVO  VARCHAR(50)
	DECLARE  @CATEGORIA VARCHAR (30)
	DECLARE  @PRECO     NUMERIC(10,2)
	DECLARE  @DATA      DATETIME
	DECLARE  @USUARIO   VARCHAR (30)
	DECLARE  @MENSAGEM  VARCHAR (100)

	 SELECT @PRODUTO     = NOME       FROM DELETED
	 SELECT @PRODUTONOVO = NOME       FROM INSERTED
	 SELECT @CATEGORIA   = CATEGORIA  FROM INSERTED  
	 SELECT @PRECO       = PRECO      FROM INSERTED 
	 
	 SELECT @DATA        = GETDATE()
	 SELECT @USUARIO     = SUSER_NAME()
	 SELECT @MENSAGEM    = 'ATUALIZAÇÃO DE NOME REALIZADA COM SUCESSO'

	 PRINT ('ATUALIZAÇÃO DE NOME REALIZADA COM SUCESSO')

	 INSERT INTO HIST_NOME
	 (PRODUTO,PRODUTONOVO,CATEGORIA,PRECO,DATA,USUARIO,MENSAGEM)
	 VALUES
	 (@PRODUTO,@PRODUTONOVO,@CATEGORIA,@PRECO,@DATA,@USUARIO,@MENSAGEM)

END
GO